### ISSUE TITLE
setTextureFilter causes segfault

### ISSUE THREAD

**Issue by KelvinShadewing** [KelvinShadewing/brux-gdk#65]
Here's the code for the function:
```
void setTextureFilter(int tex, int filter) {
	SDL_ScaleMode sm = (SDL_ScaleMode)min(max(filter, 0), 2);

	if(tex > 0 && tex < vcTextures.size() && vcTextures[tex] != 0)
		SDL_SetTextureScaleMode(vcTextures[tex], sm);
	else
		xyPrint("WARNING: Texture not found!");
}
```

From what few examples I can find, I'm using the function `SDL_SetTextureScaleMode` correctly, but it causes a crash every time.

**Comment by Vankata453** [comment]
Tried this on latest `unstable` and there's no crash for me. I presume this was fixed along the way?

**Comment by KelvinShadewing** [comment]
Probably was. I'll close this.
