### ISSUE TITLE
Move from miniswig to Simple Squirrel (SuperTux fork)

### ISSUE THREAD

**Issue by tulpenkiste** [KelvinShadewing/brux-gdk#66]
I personally believe miniswig makes working with the brux codebase quite daunting and not at all a fun experience to work with.
Not too long ago, the SuperTux project hard forked [SimpleSquirrel](https://github.com/SuperTux/simplesquirrel) (along with also preparing to ditch miniswig in favour of simplesquirrel) and, imo, using SimpleSquirrel makes dealing with Squirrel a lot more understandable and easier while not having particularly many trade offs.

**Comment by KelvinShadewing** [comment]
What we have currently feels pretty simple to me, just add functions to an API file. What kind of changes would we need to do to use this, and how would the new workflow go?

**Comment by tulpenkiste** [comment]
> What we have currently feels pretty simple to me, just add functions to an API file. What kind of changes would we need to do to use this, and how would the new workflow go?

The changes we could make is to remove a lot of the functions within `rte/src/api` as they would no longer be required (due to them being basic wrapper functions for squirrel) and instead use `ssq::VM::addFunc` (or `ssq::VM::setConst` for constants).

Additionally, we would also be able to remove a fair of compilation steps as it doesn't require generating build/bin/miniswig to parse the API (as its handled entirely via a shared/static library).
We could probably cut down on a lot of C++ files in the long run.

Alongside this, simplesquirrel also lets programmers extend C++ classes from inside of squirrel. We aren't using this at the moment but it is something to keep in mind.

**Comment by hexaheximal** [comment]
I actually agree with tulip on this one. I hate dealing with Miniswig and SimpleSquirrel looks so much better.

I am very concerned about how something like SimpleSquirrel would work if we were to port Brux GDK to pure C, however, we're not doing that right now (at least I'm not), and it isn't really worth the effort either way.

(yes, I'm replying via email, and yes I'm still mad at GitHub)

- hexaheximal

**Comment by Vankata453** [comment]
I can try to implement this sometime, since I've gotten a good understanding of SimpleSquirrel from having implemented it into SuperTux. However, I'm not sure when I'll be able to do that.

**Comment by Vankata453** [comment]
@KelvinShadewing Now that #71 is merged, this can be closed. Not sure why GitHub didn't do it.
